import Link from "next/link";
import { RefreshCw } from "lucide-react";
import type { Finding, Scan, Summary } from "@/lib/api";
import {
  Card,
  Notice,
  RiskBadge,
  SeverityBar,
  Stat,
  levelFromScore,
} from "@/components/ui";

export default function OverviewTab({
  projectId,
  scan,
  summary,
  findings,
  onRerunAi,
  rerunning,
}: {
  projectId: string;
  scan: Scan;
  summary: Summary;
  findings: Finding[];
  onRerunAi: () => void;
  rerunning: boolean;
}) {
  const score = summary.overall_risk_score;
  const top = findings.slice(0, 5);

  return (
    <div className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Stat
          label="Overall risk"
          value={score === null ? "n/a" : `${score} / 100`}
          hint={score === null ? undefined : <RiskBadge level={levelFromScore(score)} />}
        />
        <Stat label="Findings" value={summary.total_vulnerabilities} />
        <Stat label="Dependencies" value={summary.total_dependencies} />
        <Stat label="Vulnerable dependencies" value={summary.vulnerable_dependencies} />
      </div>

      <Card title="Findings by risk level">
        <SeverityBar counts={summary.vulnerabilities_by_risk_level} />
        {summary.context && (
          <p className="mt-4 text-xs text-slate-500">
            Scored with context: {summary.context.internet_facing ? "internet-facing" : "not internet-facing"},{" "}
            {summary.context.criticality} criticality.
          </p>
        )}
      </Card>

      {scan.warnings.length > 0 && (
        <Notice tone="warn">
          <div className="font-medium">Scan notes</div>
          <ul className="mt-1 list-disc pl-5">
            {scan.warnings.map((warning, index) => (
              <li key={index}>{warning}</li>
            ))}
          </ul>
        </Notice>
      )}

      <div className="grid gap-6 lg:grid-cols-2">
        <Card title="Top priorities">
          {top.length === 0 && <p className="text-sm text-slate-400">No vulnerabilities found.</p>}
          <ul className="divide-y divide-slate-800">
            {top.map((finding) => (
              <li key={finding.id} className="flex items-center justify-between gap-3 py-2 text-sm">
                <Link
                  href={`/projects/${projectId}/scans/${scan.id}/findings/${finding.id}`}
                  className="min-w-0 hover:underline"
                >
                  <span className="text-slate-500">#{finding.priority_rank}</span>{" "}
                  <span className="font-medium">
                    {finding.package_name}@{finding.package_version}
                  </span>
                  <div className="truncate text-xs text-slate-400">{finding.osv_id}</div>
                </Link>
                <div className="flex shrink-0 items-center gap-2">
                  <span className="text-slate-300">{finding.risk_score}</span>
                  <RiskBadge level={finding.risk_level} />
                </div>
              </li>
            ))}
          </ul>
        </Card>

        <Card
          title="AI security summary"
          action={
            <button
              onClick={onRerunAi}
              disabled={rerunning}
              className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-100 disabled:opacity-50"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${rerunning ? "animate-spin" : ""}`} />
              Re-run
            </button>
          }
        >
          {summary.ai_summary ? (
            <div className="space-y-3 text-sm">
              <p className="whitespace-pre-wrap text-slate-300">{summary.ai_summary.executive_summary}</p>
              <ul className="list-disc space-y-1 pl-5 text-slate-300">
                {summary.ai_summary.top_priorities.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
              <p className="text-xs text-slate-500">
                AI-generated by {summary.ai_summary.model}. Verify against the advisory before acting.
              </p>
            </div>
          ) : (
            <Notice>
              AI analysis is not available{summary.ai_message ? `: ${summary.ai_message}` : ""}. The risk
              scores, attack paths and remediation hints are deterministic and unaffected.
            </Notice>
          )}
        </Card>
      </div>
    </div>
  );
}