"""dependencies and vulnerabilities

Revision ID: 069c6fa82e22
Revises: 99da01f4c026
Create Date: 2026-10-07 11:13:17.641201
"""
from alembic import op
import sqlalchemy as sa


revision = '069c6fa82e22'
down_revision = '99da01f4c026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('purl', sa.String(length=700), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'ecosystem', 'name', 'version', name='uq_dependencies_component')
    )
    op.create_index(op.f('ix_dependencies_scan_id'), 'dependencies', ['scan_id'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_edges_scan_id'), 'dependency_edges', ['scan_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_id', sa.Uuid(), nullable=False),
    sa.Column('osv_id', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('known_exploited', sa.Boolean(), nullable=True),
    sa.Column('fixed_versions', sa.JSON(), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependency_id', 'osv_id', name='uq_vulnerabilities_dependency_osv')
    )
    op.create_index(op.f('ix_vulnerabilities_dependency_id'), 'vulnerabilities', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    op.add_column('scans', sa.Column('source_filename', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('warnings', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'warnings')
    op.drop_column('scans', 'source_filename')
    op.drop_index(op.f('ix_vulnerabilities_scan_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_dependency_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_dependency_edges_scan_id'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_dependencies_scan_id'), table_name='dependencies')
    op.drop_table('dependencies')
    # ### end Alembic commands ###