"""risk engine and ai analysis

Revision ID: a8b1f88f6bc8
Revises: 069c6fa82e22
Create Date: 2026-10-07 12:34:48.254673
"""
from alembic import op
import sqlalchemy as sa


revision = 'a8b1f88f6bc8'
down_revision = '069c6fa82e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('internet_facing', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('projects', sa.Column('criticality', sa.String(length=10), server_default='medium', nullable=False))
    op.add_column('scans', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('scans', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('scans', sa.Column('ai_status', sa.String(length=20), nullable=True))
    op.add_column('scans', sa.Column('ai_message', sa.String(length=300), nullable=True))
    op.add_column('scans', sa.Column('ai_summary', sa.JSON(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('risk_level', sa.String(length=10), nullable=True))
    op.add_column('vulnerabilities', sa.Column('priority_rank', sa.Integer(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('component_role', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('risk_breakdown', sa.JSON(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('attack_path', sa.JSON(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'ai_analysis')
    op.drop_column('vulnerabilities', 'attack_path')
    op.drop_column('vulnerabilities', 'risk_breakdown')
    op.drop_column('vulnerabilities', 'component_role')
    op.drop_column('vulnerabilities', 'priority_rank')
    op.drop_column('vulnerabilities', 'risk_level')
    op.drop_column('vulnerabilities', 'risk_score')
    op.drop_column('scans', 'ai_summary')
    op.drop_column('scans', 'ai_message')
    op.drop_column('scans', 'ai_status')
    op.drop_column('scans', 'context')
    op.drop_column('scans', 'risk_score')
    op.drop_column('projects', 'criticality')
    op.drop_column('projects', 'internet_facing')
    # ### end Alembic commands ###